# Generated by Django 4.2.16 on 2024-11-25 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('road_address_name', models.TextField()),
                ('distance', models.TextField()),
                ('phone', models.TextField()),
                ('place_name', models.TextField()),
                ('place_url', models.TextField()),
                ('x', models.TextField()),
                ('y', models.TextField()),
            ],
        ),
    ]
