# Generated by Django 4.2.16 on 2024-11-20 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subsidy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('name_category', models.CharField(max_length=10)),
                ('target', models.TextField()),
                ('content', models.TextField()),
                ('contact', models.TextField()),
                ('like_users', models.ManyToManyField(default=0, related_name='like_subsidies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubsidyComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('rating', models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subsidy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='subsidies.subsidy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsidy_comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
