# Generated by Django 4.2.16 on 2024-11-19 14:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subsidies', '0002_alter_subsidycomment_subsidy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsidy',
            name='like_users',
            field=models.ManyToManyField(default=0, related_name='like_subsidies', to=settings.AUTH_USER_MODEL),
        ),
    ]
