# Generated by Django 4.2.16 on 2024-11-19 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subsidies', '0003_alter_subsidy_like_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsidy',
            name='contact',
            field=models.TextField(),
        ),
    ]
