# Generated by Django 4.2.16 on 2024-11-19 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositoption',
            name='fin_prdt_cd',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='depositoption',
            name='deposit_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposit_options', to='deposits.depositproduct'),
        ),
    ]
