# Generated by Django 4.2.16 on 2024-11-19 08:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deposits', '0002_depositoption_fin_prdt_cd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositproduct',
            name='like_users',
            field=models.ManyToManyField(default=0, related_name='like_deposits', to=settings.AUTH_USER_MODEL),
        ),
    ]
