# Generated by Django 4.2.16 on 2024-11-19 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0003_alter_depositproduct_like_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositproduct',
            name='max_limit',
            field=models.IntegerField(default=0),
        ),
    ]
