# Generated by Django 4.2.16 on 2024-11-19 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0004_alter_depositproduct_max_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositproduct',
            name='max_limit',
            field=models.IntegerField(),
        ),
    ]
