# Generated by Django 4.2.6 on 2024-11-20 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='keyword',
            field=models.CharField(choices=[('적금', 'saving'), ('예금', 'deposit'), ('지원금', 'subsidy'), ('기타', 'etc')], max_length=10),
        ),
    ]
