# Generated by Django 4.2.16 on 2024-11-21 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='income',
            field=models.CharField(choices=[('0~50%', '약 100만원'), ('51~75%', '약 150만원'), ('76~100%', '약 200만원'), ('101~200%', '약 450만원'), ('200%~', '약 450초과')], max_length=20),
        ),
    ]
