# Generated by Django 4.2.16 on 2024-11-25 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='career',
            field=models.CharField(choices=[('학생', 'student'), ('회사원', 'office_worker'), ('사업자', 'business_owner'), ('아르바이트/비정규직', 'part_time'), ('무직/구직중', 'unemployed'), ('군인', 'soldier'), ('스타트업 창업자', 'startup_founder'), ('기타', 'other')], max_length=20),
        ),
    ]
