# Generated by Django 4.2.16 on 2024-11-19 13:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('savings', '0002_alter_savingoption_saving_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingproduct',
            name='like_users',
            field=models.ManyToManyField(default=0, related_name='like_savings', to=settings.AUTH_USER_MODEL),
        ),
    ]
