# Generated by Django 4.2.16 on 2024-11-19 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0003_alter_savingproduct_like_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingoption',
            name='fin_prdt_cd',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
