# Generated by Django 4.2.16 on 2024-11-23 13:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exchanges", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="exchange",
            old_name="remittance_receive",
            new_name="cash_send",
        ),
        migrations.RemoveField(
            model_name="exchange",
            name="remittance_send",
        ),
        migrations.AddField(
            model_name="exchange",
            name="cash_receive",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="exchange",
            name="country_name",
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
