# Generated by Django 4.2.16 on 2024-11-20 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='image_src',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
